### ISSUE TITLE
Tileset not working

### ISSUE THREAD

**Issue by jasminejamjelly** [dbakewel/lan-caster#2]
**What do you need help with?**
Hi there! I'm wondering if there are any restrictions on how tilesets are drawn that might make it so the game cannot run? I'm aware that tiles cannot be rotated, but I was wondering if there were any other restrictions on how tiles are implemented that might break the game? After adding a tile from a certain tileset, it gives me an error... Thank you ! 
(I've tried to attach an image but I'm not sure if it attached!)

![Capture](https://user-images.githubusercontent.com/64162099/171698279-a5e96fc8-1b0a-405d-9814-b0132e6dfbda.PNG)

**Comment by dbakewel** [comment]
Please answer the questions below:

Is that the output from the client or the server?

Please look in the Json file for the map. Do you see the tile set listed in the map? 
Normally you will see a list of all tile sets for the map near the bottom of the Json file. If you don't see it, you can use add external tile set for the map in Tiled. That problem can occur when you don't actually use a tile from the tile set in the map.

If that does not help, then please post a link to your Repository and let me know which map and tileset are the problem?

**Comment by jasminejamjelly** [comment]
oh that helped a lot ! i removed a tileset i wasn't using and it worked! thanks a lot :D

**Comment by dbakewel** [comment]
OK, great, I'll put in some better logging so this error is more obvious in the future.
