### ISSUE TITLE
Possible spelling error "speachText" in engine/servermap.py under setSpriteSpeechText

### ISSUE THREAD

**Issue by Sunery030** [dbakewel/lan-caster#3]
Came across this when reading the code. Line 422 under in engine/servermap.py. Seems to be a minor error as no problems because of this are seen so far.

**Comment by dbakewel** [comment]
Yes, thanks for pointing this out. It's actually spelled wrong throughout the entire game engine. I'll do a fix in next day. Thanks

**Comment by dbakewel** [comment]
Thanks, I found 4 places where it was misspelled and fix them all. I added a pull request to your repository so you can merge in all the latest fixes.

![image](https://user-images.githubusercontent.com/11411338/171753698-11fa84c6-2ff8-4fcc-b355-8eaa848165d6.png)
