### ISSUE TITLE
UI help

### ISSUE THREAD

**Issue by Davy321** [dbakewel/lan-caster#5]
Is it possible to display anything other than text with the UI functions of the engine? (see updateInterface() in engine/client.py)

**Comment by dbakewel** [comment]
Yes, you can do this by using pygame directly. For example, pygame has functions to draw shapes: https://www.pygame.org/docs/ref/draw.html

Right now the Client class does not use pygame but you can add it. Just import pygame into your client and then use it in updateInterface().

```
import pygame
```

You can also see lots of examples in ClientMap about how to draw. Look for everything below "BLIT/DRAW SHAPE OBJECTS". That code is more complex than you need. You probably just need the pygame.draw functions.

**Comment by dbakewel** [comment]
Please let me know if that helps and close this issue if it answers the question.

**Comment by Davy321** [comment]
This worked, thank you very much :)
