### ISSUE TITLE
Is it possible to create an outOfBounds for some players, and not others?

### ISSUE THREAD

**Issue by pahu2353** [dbakewel/lan-caster#7]
**What do you need help with?**
My group is trying to make a 'base' for players of one team to spawn/respawn on; players from the other team should not be able to walk into this base. How would we make it so the base is outOfBounds to an opposing team? We have a ['team'] attribute for players of both teams in the .json already. 

Thank you so much!

**Comment by dbakewel** [comment]
Yes, you can set which layers are considered by map.Map.checkLocation(). This method is used to check if a new location for a sprite is valid. It normally stops sprites from entering an outOfBounds zone. Each sprite can have the layers to be considered set by adding a 'checkLocationOn' attribute to the sprite. 

The default (same as not having 'checkLocationOn') is:
```
sprite['checkLocationOn'] = ['outOfBounds','inBounds','sprites']
```

If you put in an empty list then the sprite will collide with nothing except the edge of the map:
```
sprite['checkLocationOn'] = []
```


So if you want the normal behavior except without 'outOfBounds' use:
```
sprite['checkLocationOn'] = ['inBounds','sprites']
```

You can see this code in action in demo2: demo2.server.setCollsion(). That code makes it so players can overlap with other players and monsters. But monsters can't overlap with other monsters. It also uses collisionType == 'circle' to make that work.

Let me know if that helps and close this issue if you don't have any follow up questions.

**Comment by dbakewel** [comment]
Sorry that did not really answer your question. I'll post some more in a bit.

**Comment by dbakewel** [comment]
Here is one way to do it:

1) Make sure each player is identified as to which team they are on. I'm going to assume each player sprite has a property with their team name. e.g. 'team': 'blue' in Tiled. This will show up as sprite['prop-blue'] == 'blue' in the python code.

2) On the outOfBounds layer, add rects that cover each base and add a 'team' property to the rects. For the blue teams base, you would have a property of 'team': 'blue' for all rects that cover the base. This means these rects should not be used for players with 'team': 'blue'.

3) Now you need to extend map.Map.checkLocation(). I suggest you do this in your servermap subclass. Something like this should work but the code below is untested:

```
from engine.geometry import collidesFast

    def checkLocation(self, object, newAnchorX, newAnchorY):
        """EXTEND map.Map.checkLocation()"""

        allowMove = super().checkLocation(object, newAnchorX, newAnchorY)
        
        # if the object is not allowed to move then check if it is a player trying to move into their own base.
        if (not allowMove) and object['type'] == 'player' and 'prop-team' in object:
                # create collidesWith object that is where the player would be if the move were allowed.
                newX = newAnchorX - (object['anchorX'] - object['x'])
                newY = newAnchorY - (object['anchorY'] - object['y'])
                collidesWith = {
                    'x':newX,
                    'y':newY,
                    'anchorX':newAnchorX,
                    'anchorY':newAnchorY,
                    'width':object['width'],
                    'height':object['height'],
                    'collisionType':object['collisionType']
                }

                # if the player is trying to enter an outOfBounds of their own base then allow it.
                for o in self['outOfBounds']:
                    if 'prop-team' in o and o['prop-team'] == object['prop-team']:
                        if collidesFast(collidesWith,collidesWith['collisionType'], o,o['collisionType']) and o != object:
                            return True
        return allowMove
```

**Comment by pahu2353** [comment]
Thank you so much! That helps a lot :)
